name: CI/CD action

on:
  push:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    env:
      PG_NAME: ${{ secrets.PG_NAME }}
      PG_USER: ${{ secrets.PG_USER }}
      PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
      PG_HOST: ${{ secrets.PG_HOST }}
      PG_PORT: ${{ secrets.PG_PORT }}
    services:
      postgres_main:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ env.PG_USER }}
          POSTGRES_PASSWORD: ${{ env.PG_PASSWORD }}
          POSTGRES_DB: ${{ env.PG_NAME }}
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 10s
          --health-retries 10

    steps:
      - name: Проверить изменения
        uses: actions/checkout@v3

      - name: Установка python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Линтер
        run: |
          flake8 articles --exclude migrations --ignore E501,F401,E302,W293,W391,W292
      - name: Тесты
        run: python manage.py test
        env:
          PG_NAME: ${{ env.PG_NAME }}
          PG_USER: ${{ env.PG_USER }}
          PG_PASSWORD: ${{ env.PG_PASSWORD }}
          PG_HOST: ${{ env.PG_HOST }}
          PG_PORT: ${{ env.PG_PORT }}
      - name: Check environment variables
        run: |
          echo "PG_NAME: ${{ env.PG_NAME }}"
          echo "PG_USER: ${{ env.PG_USER }}"
          echo "PG_PASSWORD: ${{ env.PG_PASSWORD }}"
          echo "PG_HOST: ${{ env.PG_HOST }}"
          echo "PG_PORT: ${{ env.PG_PORT }}"


